
import {
    describe,
    it,
    expect,
    vi,
    beforeEach,
    afterAll,
} from 'vitest'

import Form from '~/vue/lib/Form'
import Errors from '~/lib/Errors'
import { ValidationError } from '~/index'

type TestData = {
    name: string
    email: string
}

/**
 * Generated by ChatGPT
 */
describe('Form', () => {
    let form: Form<TestData>

    beforeEach(() => {
        form = new Form<TestData>({ name: '', email: '' }, (data) => {
            const errors = new Errors()

            if (!(data as any).name) {
                errors.add({ name: 'Name is required' })
            }

            if (!(data as any).email || !/.+@.+\..+/.test((data as any).email)) {
                errors.add({ email: 'Invalid email format' })
            }

            if (errors.any()) {
                throw new ValidationError(errors)
            }
        })
    })

    it('initializes with default data and errors', () => {
        expect(form.data).toEqual({ name: '', email: '' })
        expect(form.initialData).toEqual({ name: '', email: '' })
        expect(form.errors).toBeInstanceOf(Errors)
        expect(form.loading.value).toBe(false)
        expect(form.hasChanges).toBe(false)
    })

    it('updates form data and detects changes', () => {
        form.updateData({ name: 'John' })
        expect(form.data.name).toBe('John')
        expect(form.hasChanges).toBe(true)
    })

    it('resets data to initial values', () => {
        form.updateData({ name: 'John', email: 'john@example.com' })
        expect(form.hasChanges).toBe(true)
        form.reset()
        expect(form.data).toEqual({ name: '', email: '' })
        expect(form.hasChanges).toBe(false)
    })

    it('validates fields correctly', () => {
        form.data.name = ''
        const isValidName = form.validateField('name')
        expect(isValidName).toBe(false)
        expect(form.errors.has('name')).toBe(true)
        expect(form.errors.get('name')).toContain('Name is required')

        form.data.email = 'invalid-email'
        const isValidEmail = form.validateField('email')
        expect(isValidEmail).toBe(false)
        expect(form.errors.has('email')).toBe(true)
        expect(form.errors.get('email')).toContain('Invalid email format')
    })

    it('validates the entire form', () => {
        form.validate()
        expect(form.errors.has('name')).toBe(true)
        expect(form.errors.has('email')).toBe(true)

        form.updateData({ name: 'John', email: 'john@example.com' })
        form.validate()
        expect(form.errors.any()).toBe(false)
    })

    it('updates the initial data', () => {
        form.updateInitialData({ name: 'Jane', email: 'jane@example.com' })
        expect(form.initialData).toEqual({ name: 'Jane', email: 'jane@example.com' })
        expect(form.data).toEqual({ name: 'Jane', email: 'jane@example.com' })
        expect(form.hasChanges).toBe(false)
    })

    it('useSubmit executes resolver successfully', async () => {
        const mockResolver = vi.fn().mockResolvedValue('Success')

        const submit = form.useSubmit(mockResolver, { resetOnSuccess: true })

        // Set valid data before submission
        form.updateData({ name: 'John Doe', email: 'john@example.com' })

        await submit()

        expect(mockResolver).toHaveBeenCalled()
        expect(form.sent.value).toBe(true)
        expect(form.error.value).toBe(undefined)
        expect(form.hasChanges).toBe(false)
    })

    it('useSubmit handles validation failure', async () => {
        const mockResolver = vi.fn()
        const submit = form.useSubmit(mockResolver)

        await submit()

        expect(mockResolver).not.toHaveBeenCalled()
        expect(form.errors.has('name')).toBe(true)
    })

    it('handles submission errors gracefully', async () => {
        const mockResolver = vi.fn().mockRejectedValue(new Error('Submission failed'))
        const onError = vi.fn()

        const submit = form.useSubmit(mockResolver, { onError })

        // Set valid data before submission
        form.updateData({ name: 'John Doe', email: 'john@example.com' })

        await expect(submit()).rejects.toThrow('Submission failed')

        expect(mockResolver).toHaveBeenCalled()
        expect(onError).toHaveBeenCalled()
        expect(form.error.value).toBeInstanceOf(Error)
    })
})

describe('Validation', () => {
    it('integrates with any validation', () => {
        const form = new Form(
            { name: 'Jo' },
            (data) => {
                const errors = new Errors()

                if ((data as any).name && (data as any).name.length < 3) {
                    errors.add({ name: 'Too short' })
                }

                throw new ValidationError(errors)
            },
        )

        form.validate()

        expect(form.errors.get('name')).toContain('Too short')
    })
})
