/* eslint-disable no-empty-function */
import {
    describe,
    it,
    expect,
    vi,
    beforeEach,
    afterAll,
} from 'vitest'

import Form from '~/vue/lib/Form'
import Errors from '~/lib/Errors'

type TestData = {
    name: string
    email: string
}

const validationRules = {
    name: [
        (value: any) => (!value ? 'Name is required' : undefined),
        (value: any) => (value.length < 3 ? 'Name must be at least 3 characters' : undefined),
    ],
    email: [
        (value: any) => (!value ? 'Email is required' : undefined),
        (value: any) => (!/.+@.+\..+/.test(value) ? 'Invalid email format' : undefined),
    ],
}

/**
 * Generated by ChatGPT
 */
describe('Form', () => {
    let form: Form<TestData>

    beforeEach(() => {
        form = new Form<TestData>({ name: '', email: '' }, validationRules)
        // Mock console to avoid cluttering test output
        vi.spyOn(console, 'log').mockImplementation(() => {})
        vi.spyOn(console, 'warn').mockImplementation(() => {})
    })

    afterAll(() => {
        vi.restoreAllMocks()
    })

    it('initializes with default data and errors', () => {
        expect(form.data).toEqual({ name: '', email: '' })
        expect(form.initialData).toEqual({ name: '', email: '' })
        expect(form.errors).toBeInstanceOf(Errors)
        expect(form.loading.value).toBe(false)
        expect(form.hasChanges).toBe(false)
    })

    it('updates form data and detects changes', () => {
        form.updateData({ name: 'John' })
        expect(form.data.name).toBe('John')
        expect(form.hasChanges).toBe(true)
    })

    it('resets data to initial values', () => {
        form.updateData({ name: 'John', email: 'john@example.com' })
        expect(form.hasChanges).toBe(true)
        form.reset()
        expect(form.data).toEqual({ name: '', email: '' })
        expect(form.hasChanges).toBe(false)
    })

    it('validates fields correctly', () => {
        const isValidName = form.validateField('name', '')
        expect(isValidName).toBe(false)
        expect(form.errors.has('name')).toBe(true)
        expect(form.errors.get('name')).toContain('Name is required')

        const isValidEmail = form.validateField('email', 'invalid-email')
        expect(isValidEmail).toBe(false)
        expect(form.errors.has('email')).toBe(true)
        expect(form.errors.get('email')).toContain('Invalid email format')
    })

    it('validates the entire form', () => {
        const isValid = form.validate()
        expect(isValid).toBe(false)
        expect(form.errors.has('name')).toBe(true)
        expect(form.errors.has('email')).toBe(true)

        form.updateData({ name: 'John', email: 'john@example.com' })
        const isValidAfterUpdate = form.validate()
        expect(isValidAfterUpdate).toBe(true)
        expect(form.errors.any()).toBe(false)
    })

    it('updates the initial data', () => {
        form.updateInitialData({ name: 'Jane', email: 'jane@example.com' })
        expect(form.initialData).toEqual({ name: 'Jane', email: 'jane@example.com' })
        expect(form.data).toEqual({ name: 'Jane', email: 'jane@example.com' })
        expect(form.hasChanges).toBe(false)
    })

    it('useSubmit executes resolver successfully', async () => {
        const mockResolver = vi.fn().mockResolvedValue('Success')

        const submit = form.useSubmit(mockResolver, { resetOnSuccess: true })

        // Set valid data before submission
        form.updateData({ name: 'John Doe', email: 'john@example.com' })

        await submit()

        expect(mockResolver).toHaveBeenCalled()
        expect(form.sent.value).toBe(true)
        expect(form.error.value).toBe(undefined)
        expect(form.hasChanges).toBe(false)
    })

    it('useSubmit handles validation failure', async () => {
        const mockResolver = vi.fn()
        const submit = form.useSubmit(mockResolver)

        await submit()

        expect(mockResolver).not.toHaveBeenCalled()
        expect(form.errors.has('name')).toBe(true)
    })

    it('handles submission errors gracefully', async () => {
        const mockResolver = vi.fn().mockRejectedValue(new Error('Submission failed'))
        const onError = vi.fn()

        const submit = form.useSubmit(mockResolver, { onError })

        // Set valid data before submission
        form.updateData({ name: 'John Doe', email: 'john@example.com' })

        await expect(submit()).rejects.toThrow('Submission failed')

        expect(mockResolver).toHaveBeenCalled()
        expect(onError).toHaveBeenCalled()
        expect(form.error.value).toBeInstanceOf(Error)
    })
})
